--1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME

--2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC

--3
SELECT STUDENT_NAME "학생 이름", TO_CHAR(ENTRANCE_DATE, 'YYMMDD') 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE'강원%')
AND ENTRANCE_DATE LIKE '9%'
ORDER BY STUDENT_NAME

--4
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN 

--5
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO LIKE '200402'
ORDER BY POINT DESC


--6
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
ORDER BY STUDENT_NAME


--7
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS
NATURAL JOIN TB_DEPARTMENT


--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS

--9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM 


--10
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", POINT "전체 평점"
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME LIKE '음악학과'
GROUP BY 


--SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", POINT "전체 평점"
--FROM (SELECT *
--FROM TB_STUDENT
--NATURAL JOIN TB_GRADE)
--JOIN TB_DEPARTMENT ON(DEPARTMENT_NO)
--WHERE DEPARTMENT_NAME = '음악학과'

-- 11


-- 12
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT, TB_GRADE
WHERE STUDENT_NAME = '김혜원'